package main

import (
	"database/sql"
	"log"

	_ "github.com/lib/pq"

	"github.com/basudebpalwebdev/admybrand-friend-finder/api"
	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/basudebpalwebdev/admybrand-friend-finder/docs"
)

// @title Friend Finder API
// @version 1.0
// @description This is a sample swagger for Friend Finder
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email fiber@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:9999
// @BasePath /
func main() {
	dbConn, err := sql.Open("postgres", "postgresql://basu:Basudeb@2021@localhost:5432/admybrand_friend_finder?sslmode=disable")
	if err != nil {
		log.Fatal("Cannot connect to the database :", err)
	}
	webServer := api.NewServer(dbConn)
	webServer.Start("localhost:9999")
}
