// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type User struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	Description string    `json:"description"`
	Dob         time.Time `json:"dob"`
	Address     string    `json:"address"`
	CreatedAt   time.Time `json:"created_at"`
}
